# Generated by Django 4.2 on 2023-05-04 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_rename_books_book"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("follows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follows",
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
