# Generated by Django 4.2 on 2023-05-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_rename_books_book"),
        ("copies", "0003_alter_copy_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copy",
            name="book",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copies",
                to="books.book",
            ),
        ),
    ]
